name: Python CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Permite execução manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install Poetry
      run: pip install poetry
    
    - name: Install dependencies
      run: poetry install --no-root
    
    - name: Run tests with pytest
      run: poetry run pytest tests/ -v
    
    - name: Lint with Flake8
      run: poetry run flake8 src/
    
    - name: Check types with mypy
      run: poetry run mypy src/

      #