name: CI de Qualidade e Testes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  qualidade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar ferramentas
      run: |
        pip install poetry flake8 pylint mypy radon
        poetry install

    # Etapa 4.1 - Testes
    - name: Executar testes pytest
      run: poetry run pytest tests/

    # Etapa 4.2 - Flake8
    - name: Verificar estilo (Flake8)
      run: poetry run flake8 src/ --count --show-source --statistics

    # Etapa 4.3 - Pylint
    - name: Verificar qualidade (Pylint)
      run: poetry run pylint src/ --exit-zero

    # Etapa 4.4 - MyPy
    - name: Verificar tipagem (MyPy)
      run: poetry run mypy src/

    # Etapa 4.5 - Radon
    - name: Analisar complexidade (Radon)
      run: |
        echo "Complexidade Ciclomática:"
        poetry run radon cc src/
        echo "\nÍndice de Manutenibilidade:"
        poetry run radon mi src/