name: Python CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: 'AulaPratica'

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install --with dev
      working-directory: ${{ github.workspace }}/AulaPratica

    - name: Run tests with pytest
      run: |
        poetry run pytest tests/ -v \
          --junitxml=test-results/results.xml \
          --cov=src \
          --cov-report=xml:coverage.xml \
          --cov-report=html:cov_html
      working-directory: ${{ github.workspace }}/AulaPratica

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          ${{ github.workspace }}/AulaPratica/test-results/
          ${{ github.workspace }}/AulaPratica/coverage.xml
          ${{ github.workspace }}/AulaPratica/cov_html/

    - name: Run Flake8
      run: poetry run flake8 src/
      working-directory: ${{ github.workspace }}/AulaPratica

    - name: Run Pylint
      run: poetry run pylint src/ --output-format=json:pylint_results.json || true
      working-directory: ${{ github.workspace }}/AulaPratica

    - name: Upload lint results
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: ${{ github.workspace }}/AulaPratica/pylint_results.json

    - name: Run Mypy
      run: poetry run mypy src/ --html-report mypy_report
      working-directory: ${{ github.workspace }}/AulaPratica

    - name: Run Radon
      run: |
        poetry run radon cc src/ -a > radon_results.txt
        poetry run radon mi src/ >> radon_results.txt
      working-directory: ${{ github.workspace }}/AulaPratica

    - name: Upload quality reports
      uses: actions/upload-artifact@v3
      with:
        name: quality-reports
        path: |
          ${{ github.workspace }}/AulaPratica/mypy_report/
          ${{ github.workspace }}/AulaPratica/radon_results.txt